language: go

go:
  - 1.12.x

node_js:
  - 12.18.4

# make frontend all won't work. The frontend assets have to be already built at the time of
# evaluating the Makefile first time, so for now I do it in two turns.
script: make frontend && make all
